[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = "release"
