[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'kisqragi/preview-markdown.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
on_ft = ['python']
merged=0
rev="release"
hook_source = '''
source ~/.config/nvim/coc.rc.vim
'''
